import Head from "next/head";
import Image from "next/image";
import { BottomCTA } from "../components/BottomCTA";

import { Hero } from "../components/Hero";
import { Projects } from "../components/Projects";
import { Skills } from "../components/Skills";

import { Footer } from "../components/Footer";
import { Services } from "../components/Services";

export default function Home() {
  return (
    <div className="bg-blueGray-100 dark:bg-black">
      <Head>
        <title>Ricard Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" p-0 mx-auto">
        <Hero />

        <Services />

        <Skills />

        <Projects />

        {/* <Timeline /> */}

        <BottomCTA />
      </main>
    </div>
  );
}
