import Head from "next/head";
import Image from "next/image";
import { ButtonOne } from "../components/ButtonOne";
import { Hero } from "../components/Hero";
import { Projects } from "../components/Projects";
import { Skills } from "../components/Skills";
import { Timeline } from "../components/Timeline";

export default function Home() {
  return (
    <div className="bg-blueGray-100 dark:bg-black">
      <Head>
        <title>Ricard Codes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" p-0 max-w-7xl mx-auto">
        <Hero />

        <Skills />

        <Projects />

        <Timeline />
      </main>
    </div>
  );
}
